# Generated by Django 3.2 on 2021-05-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_account_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('ManID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=9999)),
                ('ManID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity_available', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=9999)),
                ('ManID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturer')),
                ('Tags', models.ManyToManyField(to='main.ItemCategory')),
            ],
        ),
    ]
