# Generated by Django 3.2 on 2021-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ordercontains'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='DateOfBirth',
            field=models.DateTimeField(null=True),
        ),
    ]
