# Generated by Django 3.2 on 2021-05-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('main', '0004_account_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerlogo',
            name='ManID',
        ),
        migrations.AlterField(
            model_name='order',
            name='ItemsInOrder',
            field=models.ManyToManyField(to='catalogue.Items'),
        ),
        migrations.AlterField(
            model_name='ordercontains',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.items'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='ManufacturerLogo',
        ),
    ]
