# Generated by Django 3.2 on 2021-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210509_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.IntegerField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=255)),
                ('AccountPass', models.CharField(max_length=255)),
                ('ProfilePic', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateTimeField(null=True)),
            ],
        ),
    ]
