# Generated by Django 3.2 on 2021-05-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
