# Generated by Django 3.2 on 2021-05-09 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userinfo_accountconnected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=255)),
            ],
        ),
    ]
