# Generated by Django 3.2 on 2021-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='Image',
            field=models.ImageField(null=True, upload_to='static/images/userimages'),
        ),
    ]
