# Generated by Django 3.2 on 2021-05-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='Image',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
