# Generated by Django 3.2 on 2021-05-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0013_alter_userimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
                ('HistoryStr', models.CharField(max_length=255)),
            ],
        ),
    ]
