# Generated by Django 3.2 on 2021-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Image_extra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
