# Generated by Django 3.2 on 2021-05-12 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_order_datepurchased'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False,
                                    verbose_name='ID')),
                ('AccountConnected',
                 models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('PostalCode', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=255)),
                ('HouseNum', models.IntegerField()),
                ('MobilePhone', models.CharField(max_length=63)),
                ('Email', models.CharField(max_length=255)),
                ('SSN', models.CharField(max_length=255)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
