# Generated by Django 3.2 on 2021-05-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210512_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ShippingInfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
