# Generated by Django 3.2 on 2021-05-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210512_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='Promo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promocodes'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='TotalPrice',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
