# Generated by Django 3.2 on 2021-05-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210512_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TotalPrice',
        ),
    ]
