# Generated by Django 3.2 on 2021-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210512_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TotalPrice',
            field=models.FloatField(default=0),
        ),
    ]
