# Generated by Django 3.2 on 2021-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210513_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontains',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
