# Generated by Django 3.2 on 2021-05-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0028_alter_order_shippinginfoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SessionConnected',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
